name: the-power-workflow-simple
on:
  pull_request:
    types: [closed]
jobs:
  the-power-actions-demo:
    runs-on: ubuntu-latest
    steps:

      - name: check-curl-version
        run: |
          echo Security issue?
